### ISSUE TITLE
Performance Tuning for Reliable Grasping While Walking and Determination of Object Manipulation Workspace.

### ISSUE THREAD

**Issue by vigisushrutha23** [hsp-iit/project-ergocub#124]
At the moment there is a bottleneck for the grasping performance due the issue https://github.com/robotology/icub-tech-support/issues/1641. This prevents us from performing any meaningful bimanual experiments. Once this is solved, we have the following tasks.

- [x] Ensure that for at least one cardboard the real robot has consistent grasping and manipulation capabilities.
- [x] Ensure that the same is repeatable while walking.
- [ ] Obtain plots of footsteps, arm joint extremes to quantitatively analyse the shift in robot foorptint while moving the object This should give us a rough possible workspace for the object manipulation with real object.
- [x] Perform initial experiments with just Walking+Bimanual in the area behind the desk in robot arena with manual manipulation commands.

**Comment by mebbaid** [comment]
Today I did some work during my slot on the shoulder joints tracking. The observation is as follows
- Low level tracking in stiff mode is great (e.g. `l_shoulder_roll` plot below).
![figure](https://github.com/hsp-iit/project-ergocub/assets/36491318/e3ed4122-4216-4a01-9c01-835c1f16fdf4)

- When we invoke the walking to control the shoulders using commands comming from the bi-manual manipulation, we change the mode of the joint to complient hence the poor tracking.

- The fix is very simple, we need simply (in our fork/branch of the walking) to change those lines https://github.com/SimoneMic/walking-controllers/blob/3c594f6bbbfbf04a7dac6c674697564ee4ced195/src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/iFeel_joint_retargeting/robotControl.ini#L25-L26 

and those lines 
https://github.com/SimoneMic/walking-controllers/blob/3c594f6bbbfbf04a7dac6c674697564ee4ced195/src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/iFeel_joint_retargeting/robotControl.ini#L33-L34

to all read true.

**Comment by S-Dafarra** [comment]
> * When we invoke the walking to control the shoulders using commands comming from the bi-manual manipulation, we change the mode of the joint to complient hence the poor tracking.

In this case, the culprit is https://github.com/robotology/icub-tech-support/issues/1547

**Comment by vigisushrutha23** [comment]
We were able to reliably grasp and manipulate a soft lunch bag while walking as seen in the video below. We The object roll motions seemed reliable and repeatable and will be preferred in the upcoming tests.
https://github.com/hsp-iit/project-ergocub/assets/5215434/df32326c-10c5-47fc-b310-1758c7c0621a

**Comment by vigisushrutha23** [comment]
Closing Old issues
