### ISSUE TITLE
Ensure Correct Joint Order

### ISSUE THREAD

**Issue by Woolfrey** [hsp-iit/project-ergocub#138]
We need to validate that we have the correct joint order in the config files for the `ergocub-bimanual` repository. This has to match the joint re-targeting module that AMI uses.

**Comment by S-Dafarra** [comment]
Hi @Woolfrey, for the retargeting part, we read a message that also contains the joint names: https://github.com/robotology/walking-controllers/blob/cf5fa7396e7eee11186d1d157bd8d8d27b6bd215/src/YarpUtilities/thrifts/WalkingControllers/YarpUtilities/HumanState.thrift#L23-L34

Back in time, we were used to stream a vector of joint positions only, but this was very error-prone, especially because of the order. So we decided to stream a composite message containing also the list of joint names. Then, internally (see https://github.com/robotology/walking-controllers/blob/cf5fa7396e7eee11186d1d157bd8d8d27b6bd215/src/RetargetingHelper/src/Helper.cpp#L333-L360), we match the joint names in the message with the ones specified in https://github.com/robotology/walking-controllers/blob/cf5fa7396e7eee11186d1d157bd8d8d27b6bd215/src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/iFeel_joint_retargeting/jointRetargeting.ini#L12-L15

**Comment by Woolfrey** [comment]
Thanks @S-Dafarra!

For my controller there is the option in a config file to specify the joint order. We've had it working correctly with AMI's walking controller for a few months now.

This issue was created just to document that the config files have been checked and double-checked.

**Comment by Woolfrey** [comment]
Here is the order we have in the main branch:
1. torso_pitch
2. torso_roll
3. torso_yaw
4. l_shoulder_pitch
5. l_shoulder_roll
6. l_shoulder_yaw
7. l_elbow
8. l_wrist_roll
9. l_wrist_pitch 
10. l_wrist_yaw
11. r_shoulder_pitch
12. r_shoulder_roll
13. r_shoulder_yaw 
14. r_elbow
15. r_wrist_roll
16. r_wrist_pitch
17. r_wrist_yaw

@andrearosasco @steb6 make sure you follow this when re-implementing the different actions from the ICRA demo.
